apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-exchange-price-action
  labels:
    app: momoli-price-action
spec:
  replicas: 3
  selector:
    matchLabels:
      app: momoli-price-action
  template:
    metadata:
      labels:
        app: momoli-price-action
    spec:
      containers:
        - name: momoli-price-action
          image: mzgg/crypto-exchange-price-action
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "128M"
              cpu: "500m"
            limits:
              memory: "512M"
              cpu: "1"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - momoli-price-action
              topologyKey: "kubernetes.io/hostname"
