apiVersion: v1
kind: Service
metadata:
  name: momoli-price-action-service
  labels:
    app: momoli-price-action
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: momoli-price-action
  sessionAffinity: None